mysite/myblog/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns=[
    path('signup/',views.index,name='sign_up'),
    path('logout/',views.logout,name='logout'),
    path('blog/',views.blog,name='blog'),
    path('',views.login,name='login'),
    path('post/',views.post,name='post1'),
    path('post/<int:pk>/',views.postD,name='postD'),
    path('create/',views.create,name='create'),
    path('update/<int:blog_id>/',views.update,name="update"),
    path('delete/<int:blog_id>/',views.delete,name='delete'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myblog.urls')),
]

mysite/myblog/models.py
from django.db import models

class Post(models.Model):
    username = models.CharField(max_length=50)
    postname = models.CharField(max_length=50)
    contents = models.TextField()
    created_at = models.DateTimeField('CREATED DATE',auto_now_add=True)
    modified_at = models.DateTimeField('MODIFIED DATE',auto_now=True)
    def __str__(self):
        return self.postname
# Create your models here.

mysite/myblog/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login as au_lo,logout as au_logout
from django.urls import reverse
from .models import *
import getpass
from datetime import datetime
from django.contrib import messages
from django.utils import timezone
def index(request):
    return render(request,'myblog/index.html')

def blog(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password1']
        if request.POST['password1'] == request.POST['password2']:
            User.objects.create_user(username=username,password=password)
            b = {'success' : '회원가입 성공'}
            return render(request, 'myblog/success.html',b)
        else:
            a = {'error':'비밀번호가 다릅니다'}
            return render(request, 'myblog/index.html',a)

def login(request):
    if request.method =="GET":
        return render(request,'myblog/login.html')
    elif request.method =="POST":
        username = request.POST['username']
        password = request.POST['password1']
        user = authenticate(username=username, password=password)
        if user is not None:
            au_lo(request,user)
            b = Post.objects.all()
            return redirect(reverse('main:post1'))
        else:
            error={'error':'회원정보가 일치하지 않습니다.'}
            return render(request,'myblog/login.html',error)



def post(request):
    if request.method == "POST":
        c = request.user
        post_name = request.POST['posting']
        text_name = request.POST['textname']
        a = Post(username=c,postname=post_name,contents=text_name)
        a.save()
    b = Post.objects.all()

    return render(request,'myblog/post.html',{'b':b})

def postD(request , pk):
    a = Post.objects.get(pk=pk)

    return render(request,'myblog/postD.html',{'a':a})
def create(request):
    return render(request,'myblog/create.html')

def logout(request):
    au_logout(request)
    return redirect('/')

def update(request, blog_id):
    blog = Post.objects.get(id=blog_id)
    print(request.user.username)
    print(type(blog.username))
    print(request.user.username == blog.username)
    b = Post.objects.all()
    if request.user.username != blog.username:
        messages.warning(request,'사용자가 다릅니다.')
        a = {'a': '틀렸습니다' }
        return render(request,'myblog/post.html',{'b':b,'a':a})
    if request.method =="POST":
        blog.postname = request.POST['title']
        blog.contents = request.POST['body']
        blog.modified_at = timezone.datetime.now()
        blog.save()
        b = Post.objects.all()
        return render(request,'myblog/post.html',{'b':b})
    else:
        return render(request,'myblog/update.html',{'blog':blog})

def delete(request, blog_id):
    blog = Post.objects.get(id=blog_id)
    b = Post.objects.all()
    if request.user.username != blog.username:
        messages.warning(request,'사용자가 다릅니다.')
        a = {'a': '틀렸습니다' }
        return render(request,'myblog/post.html',{'b':b,'a':a})
    else:
        blog.delete()
    #b = Post.objects.all()
    return render(request,'myblog/post.html',{'b':b})
# Create your views here.

mysite/myblog/templates/myblog/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog list</title>
</head>
<body>
    <h1>게시판 페이지</h1>
</body>
</html>

mysite/myblog/templates/myblog/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
</head>
<body>
    <form method="POST" action="{% url 'main:post1' %}">
        {% csrf_token %}
        제목: <br>
        <input type="text" name="posting"><br>
        게시물: <br>
        <textarea name="textname" cols="80" rows="15"></textarea><br>
        <input type="submit" value="게시">
    </form>
</body>
</html>

mysite/myblog/templates/myblog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>회원가입</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</head>
<body class="text-center">
<div>
    <h1>회원가입!</h1>
</div>
<div class="container">
    <form method="POST" action="{% url 'main:blog' %}">
        {% csrf_token %}
        <div class="form-group">
            아이디:<br>
            <input type="text" name="username" value=""></button><br>
        </div>
        <div class="form-group">
            비밀번호:<br>
            <input type="password" name="password1" value=""><br>
        </div>
        <div class="form-group">
            비밀번호 재입력:<br>
            <input type="password" name="password2"><br>
        </div>
        <input type="submit" value="가입"><br>
    </form>
</div>

{{error}}
{{success}}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
</body>
</html>

mysite/myblog/templates/myblog/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>



</head>

<body class="text-center">
    <div class="container">
                <div class="row mt-5">
                    <div class="col-12" text-center>
                        <h1>로그인</h1>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-12">
                        {{ error }}
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-12">
                        <form method="POST" action="{% url 'main:login' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                아이디:<br>
                                <input type="text" name="username" value=""><br>
                            </div>
                            <div class="form-group">
                                비밀번호:<br>
                                <input type="password" name="password1" value=""><br><br>
                            </div>
<!--                            아이디:<br>-->
<!--                            <input type="text" name="username" value=""><br>-->
<!--                            비밀번호:<br>-->
<!--                            <input type="password" name="password1" value=""><br><br>-->

                            <input type="submit" value="로그인" class="'btn btn-primary">&nbsp;&nbsp;&nbsp;<a href="{% url 'main:sign_up' %}">회원가입하기</a><br><br>


                        </form>
                    </div>
                </div>
            </div>

    <h3>{{error}}</h3>

</body>
</html>

mysite/myblog/templates/myblog/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</head>
<body>
{% if a %}
    <script>
        alert('사용자가 다릅니다.')
    </script>
{% endif %}
<table class="table table-hover">
    <thead>
    <tr>
        <th>아이디</th>
        <th>제목</th>
        <th>내용</th>
        <th>작성일</th>
        <th>수정일</th>
        <th>수정하기</th>
        <th>삭제하기</th>
    </tr>
    </thead>
    {% for i in b %}
    <tbody>
    <tr>
        <td>{{i.username}}</td>
        <td><a href="{% url 'main:postD' i.id %}">{{i.postname}}</a></td>
        <td>{{i.contents}}</td>
        <td>{{i.created_at}}</td>
        <td>{{i.modified_at}}</td>
        <td><a href="{% url 'main:update' i.id %}">수정하기</a></td>
        <td><a href="{% url 'main:delete' i.id %}">삭제하기</a></td>
    </tr>
    </tbody>
    {% endfor %}
</table>
<a href="{% url 'main:create' %}">게시글 작성</a><br><br>
<a href="{% url 'main:logout' %}">로그아웃</a>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
</body>
</html>

mysite/myblog/templates/myblog/postD.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<span style="background-color: #61c6ed">
    작성자: {{a.username}}
    </span><br><br>
<span style="background-color: #61c6ed">
    제목: {{a.postname}}
    </span><br><br>
<span style="background-color: #61c6ed">
    내용: {{a.contents}}<br>
</span><br>
    <a href="{% url 'main:post1' %}">게시판 돌아가기</a>
</body>
</html>

mysite/myblog/templates/myblog/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog list</title>
</head>
<body>
<div>
    <h1>{{success}}</h1>
</div>
<a href="{% url 'main:login' %}">로그인하러가기</a>


</body>
</html>

mysite/myblog/templates/myblog/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="POST" action="{% url 'main:update' blog.id %}">
        {% csrf_token %}
        <h4>제목 :</h4>
        <input type="text" name="title">
        <br><br>
        <h4>내용 :</h4>
        <textarea cols=40 rows=10 name="body"></textarea>
        <br><br>
        <input type="submit" value="수정하기">
    </form>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel = "stylesheet" href = "/static/minty_bootstrap.min.css" />
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <title>Title</title>
</head>
<body>
    {% block container %}
    {% endblock %}
</body>
</html>